"""empty message

Revision ID: 077ff178d6c2
Revises: 340305d7fcaa
Create Date: 2019-01-18 22:09:15.461461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077ff178d6c2'
down_revision = '340305d7fcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentperiod', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentperiod', 'user_name')
    # ### end Alembic commands ###
