"""empty message

Revision ID: 7a907d5b4826
Revises: deadc566e06e
Create Date: 2019-01-12 17:24:19.864110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a907d5b4826'
down_revision = 'deadc566e06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentableitem', sa.Column('rented', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentableitem', 'rented')
    # ### end Alembic commands ###
