"""empty message

Revision ID: abb9ac99bb61
Revises: 7a907d5b4826
Create Date: 2019-01-13 14:30:15.080423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb9ac99bb61'
down_revision = '7a907d5b4826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentableitem', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentableitem', 'price')
    # ### end Alembic commands ###
