"""empty message

Revision ID: d5333d296891
Revises: 2249c4a0d342
Create Date: 2019-01-10 16:11:53.129242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5333d296891'
down_revision = '2249c4a0d342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentableitem', sa.Column('photo_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentableitem', 'photo_name')
    # ### end Alembic commands ###
