"""empty message

Revision ID: deadc566e06e
Revises: d5333d296891
Create Date: 2019-01-10 19:27:48.641268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deadc566e06e'
down_revision = 'd5333d296891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentableitem', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentableitem', 'title')
    # ### end Alembic commands ###
